workflows:
  ios-native-quick-start:
    name: iOS Native
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: codemagic
    environment:
      ios_signing:
        distribution_type: development
        bundle_identifier: io.codemagic.sample.iosnative
      vars:
        BUNDLE_ID: "com.nobadi.DBMultiverse"
        XCODE_WORKSPACE: "DBMultiverse.xcworkspace"
        XCODE_SCHEME: "DBMultiverse"
        APP_STORE_APPLE_ID: 1555555551
      xcode: latest # <-- set to specific version e.g. 14.3, 15.0 to avoid unexpected updates.
      cocoapods: default